name: Setup R environment
description: 📊 Setup an R environment and add it to the PATH

inputs:
  r-version:
    description: >
      Version specifier of R to use and/or download. Can be an absolute version
      like '4.3.2' or a range like '4', '4.x', or '^4.0.0'. Also supports the
      special value 'latest' which will always match the latest release.
      Defaults to 'latest'.
    default: latest
  rtools-version:
    description: 'Exact version of Rtools to use. Default uses latest suitable
    rtools for the given version of R.'
    default: ''
  Ncpus:
    description: 'Value to set the R option `Ncpus` to.'
    default: '1'
  crayon.enabled:
    description: 'Value to set the R option `crayon.enabled` to.'
    default: 'NULL'
  remove-openmp-macos:
    description: 'If true, remove `-fopenmp` from the default compilation
    flags, e.g. `SHLIB_OPENMP_CFLAGS`, as the macOS Command Line Tools do not
    support OpenMP.'
    default: true
  http-user-agent:
    description: 'If `"default"` or `""`, sets the HTTPUserAgent option to e.g. for
      R 3.6.3 running on macOS Catalina, `"R/3.6.3 R (3.6.3
      x86_64-apple-darwin17.0 x86_64 darwin17.0) on GitHub Actions"`. If
      `"release"` sets the user agent to the default user agent for the current R
      release. Otherwise uses whatever value is passed to `http-user-agent`.'
    default: 'default'
  install-r:
    description: 'If "true" download and install R during the setup. If "false"
      use the existing installation in the GitHub Action image.'
    default: true
  windows-path-include-mingw:
    description: 'If "true" put the 64 bit mingw directory from Rtools on the
    PATH for Windows builds.'
    default: true
  update-rtools:
    description: 'Update rtools40 compilers and libraries to the latest builds.'
    default: false
  use-public-rspm:
    description: 'Use the public version of RStudio package manager available
      at https://packagemanager.rstudio.com/ to serve binaries for Linux and
      Windows.'
    default: false
  extra-repositories:
    description: 'One or more extra CRAN-like repositories to include in the `repos` global option'
    default: ''

outputs:
  cache-hit:
    description: A boolean indicating whether or not a cache was hit. Usually 'false' unless this action is used multiple times with similar versions.
  r-version:
    description: The full absolute version specifier of the R version that was installed by this action. Usually something like '4.3.2'.

runs:
  using: node20
  main: _main.mjs #=> main.ts
